version: 0.2

phases:
  pre_build:
    on-failure: ABORT
    commands:
      - codebuild-breakpoint
      - echo Logging in to Amazon ECR...
      - aws --version
      - aws ecr get-login-password --region eu-west-2 | docker login --username AWS --password-stdin <%=ecrRepo%>
      - REPOSITORY_URI=<%=ecrRepo%>
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION)
      - IMAGE_TAG=${COMMIT_HASH:=latest}
      - docker buildx create --name mybuilder --use
  build:
    on-failure: ABORT
    commands:
      - docker buildx build --push --platform linux/arm64/v8,linux/amd64 --tag <%=ecrRepo%>/<%=imageName%> .
